"""
app/models/base.py
──────────────────────────────────────────────────────────────────────────────
Declarative Base and shared mixins for all SQLAlchemy ORM models.

Conventions:
- All primary keys use UUID v4 (server-generated).
- All tables include `created_at` and `updated_at` timestamps.
- Soft-deletable entities inherit SoftDeleteMixin.
"""

from __future__ import annotations

import uuid
from datetime import datetime, timezone

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """
    SQLAlchemy Declarative Base.

    All ORM models must inherit from this class.
    Alembic's autogenerate reads metadata from Base.metadata.
    """

    pass


class TimestampMixin:
    """
    Adds `created_at` and `updated_at` columns to any model.

    - `created_at`: Set once at INSERT time via server default.
    - `updated_at`: Automatically updated on every UPDATE via onupdate.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="UTC timestamp when the record was created",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="UTC timestamp when the record was last updated",
    )


class UUIDPrimaryKeyMixin:
    """
    Adds a UUID v4 primary key column named `id`.

    Uses PostgreSQL's `gen_random_uuid()` as server default for
    atomicity — the DB generates the ID, not Python.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="UUID v4 primary key — generated by PostgreSQL",
    )


class SoftDeleteMixin:
    """
    Adds `deleted_at` for soft-delete support.

    A record is considered deleted if `deleted_at IS NOT NULL`.
    All repository queries MUST filter on `deleted_at IS NULL` by default.
    """

    deleted_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
        default=None,
        index=True,
        comment="UTC timestamp of soft delete; NULL means record is active",
    )

    @property
    def is_deleted(self) -> bool:
        """Convenience property to check soft-delete status."""
        return self.deleted_at is not None


class TenantMixin:
    """
    Adds a `tenant_id` foreign key column to logically separate SaaS data.
    
    All multi-tenant models MUST inherit this mixin.
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        nullable=False,
        index=True,
        comment="ID of the Tenant this record belongs to",
    )
